---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQWhjUTZvOUhSTkJvUnJIdDRGREcySFJKdDVCYjgyZlJEdDcvUG12dGU4UXJDClVJUHgyWXU4cloyUkxsN3ZleFZyM3BpcGZuMmNFNWpoNEtLTlRjTEREZ0c4QVRFWjhhMldMZzB6Vk41cEphQU0KNVoxTmxsV2FDTzV4Q2JVK1h4dEZxNFRLc1FnN0ptQXJXRThscTJMenorRW9SQWlXc1F3dG9Ram91a1lBL1V0MApyb0tocWR6azFMcDArdGlIeXZobnNwaEhDOUFyb3Rselcxb081SUE5ZDlTa2NkWlBVK2RCZGR1eFlXOG5uak9xCi8zYVNKNTQ0TEZncXRKQ0dWL213NGk2cXJaaFBSV2MwNnpML2NEZjI3WDVnSnNjUktCK1JwWlpKSHhGNkkvT1AKT2VhQzQvYzg0dnpGSGkwb0ZyZkhhcEJOVFpzQW5Jb0dTZm5sQXROUG1RSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSFk1V2VtR3lNeDJ6OEVXUTVHTjMzZW1nS3hxK21IRjBCejFBeVdwOWdSbEhqbDBXSVFpCnBvUzgvWVYzNnNtR0V3Ynpud21lVFlwZmRmL2V1UUFvSEhtbXJZRXo0blN5REZqYzhnaEc3K1A4QkdXMWNxckQKblcrNGRybGN4QWNKREV0eEFsYlRvWXkrVUhLaEJpdk9FRFg4dmdMRmozckZIOTFqNTJ5Zy8wbXZ3OUszVjUxbwowWkZPMC9kNmFsK291UEpQczdpeFBJV1lCc2JUcW9sNFhkdlRGYVRYczcwZlhlZVJnTmtkeFlIVjBtaTJ5OGRYCjhIVys1d05pdVordy9rVVJpV290c3g0VVFvcXkwbTk3UHdSYXpaSXlOMEpYVTJUOGpPTjk3dFRvUXFQVkJZdkcKZWNoQmVMUWhYNDZxK0JPYW1DNWlqV24rcVlrUTkraGhIdGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
#kubectl certificate approve akshay
