apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: cache
spec:
  containers:
    - name: myapp
      image: redis123
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
