apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-ssd
  volumeMode: Filesystem
  volumeName: tf-pv
