apiVersion: v1
kind: PersistentVolume
metadata:
  name: tf-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-ssd
  claimRef:
    namespace: foundry
    name: tf-pvc
